# Generated by Django 5.0.3 on 2024-04-17 06:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0003_alter_like_user_id_alter_tweet_user_id_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="banner",
            field=models.ImageField(
                default="banners/default.jpg", null=True, upload_to="banners/"
            ),
        ),
        migrations.AddField(
            model_name="profile",
            name="name",
            field=models.TextField(default="user", max_length=200),
        ),
        migrations.AlterField(
            model_name="tweet",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
